// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StreamAlerter.DatabaseRepository.Context;

namespace StreamAlerter.DatabaseRepository.Migrations
{
    [DbContext(typeof(StreamAlerterContext))]
    [Migration("20210603145752_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.6");

            modelBuilder.Entity("StreamAlerter.Entities.Streamer", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("InLive")
                        .HasColumnType("INTEGER");

                    b.HasKey("Name");

                    b.ToTable("Streamers");
                });
#pragma warning restore 612, 618
        }
    }
}
